table ip nat {
	set nat_ifaces {
		type ifname
		elements = { "eth0",
			     "eth1",
			     "eth2" }
	}

	chain postrouting {
		type nat hook postrouting priority srcnat; policy accept;
		oifname @nat_ifaces masquerade
	}
}
table inet filter {
	set br0_net {
		type ifname
		elements = { "eth0",
			     "eth3",
			     "eth6" }
	}

	set br1_net {
		type ifname
		elements = { "eth1",
			     "eth4",
			     "eth7" }
	}

	set br2_net {
		type ifname
		elements = { "eth2",
			     "eth5",
			     "eth8" }
	}

	chain forward {
		type filter hook forward priority filter; policy drop;
		ct state established,related accept
		iifname @br0_net oifname @br0_net accept
		iifname @br1_net oifname @br1_net accept
		iifname @br2_net oifname @br2_net accept
	}
}

